dependencies:
- name: prometheus-rabbitmq-exporter
  version: 0.1.4
  repository: https://kubernetes-charts.storage.googleapis.com
- name: mysql
  version: 0.10.1
  repository: https://kubernetes-charts.storage.googleapis.com
- name: rabbitmq
  version: 2.1.3
  repository: https://kubernetes-charts.storage.googleapis.com
- name: nginx-ingress
  version: 0.28.2
  repository: https://kubernetes-charts.storage.googleapis.com
